### ISSUE TITLE
DEV - Practitioners page

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#35] opened 2016-10-28 03:43 UTC
# Use cases
- [ ] Photo, name, languages, location (city, country), linkedin link
- [ ] Link to get in touch
- [ ] Add / remove practitioners
- [ ] Profile info / bio
- [ ] Quote

**Comment by smypf** [comment] 2016-11-14 06:52
Duplicate of #106

**Closed by smypf** 2016-11-14 06:52 UTC
Labels: 02. Practitioners
