### ISSUE TITLE
Practitioner name adjustments

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#172] opened 2016-12-06 02:37 UTC
Ken Osland appears twice (I tried to delete one, and ended up deleting all)
Emilia Salgado, Edwina Swan and Peter Murphy need to be deleted
Jon van Veen is actually Johan van Veen
Fabio Salverry is spelt Fabio Salaverry
 
Also, within their regions, we’d like them sorted alphabetically by surname, horizontally – if that makes sense?

**Comment by smypf** [comment] 2016-12-09 04:22
Duplicate of #173

**Closed by smypf** 2016-12-09 04:22 UTC
